# Generated by Django 4.2.10 on 2025-05-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0004_chapter_pdf_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Contador de Visualizações'),
        ),
    ]
