# Generated by Django 4.2.10 on 2025-05-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0005_manga_views_count'),
    ]

    operations = [
        # Primeiro, remover a coluna views_count se ela existir
        migrations.RemoveField(
            model_name='manga',
            name='views_count',
        ),

        # Depois, adicionar a coluna views_count novamente
        migrations.AddField(
            model_name='manga',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Contador de Visualizações'),
        ),
    ]
