# Generated by Django 4.2.10 on 2025-05-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0006_auto_20250515_1534'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Verificar se a coluna já existe antes de tentar adicioná-la
            PRAGMA table_info(mangas_manga);
            """,
            reverse_sql="""
            -- Não fazer nada na reversão
            """
        ),
    ]
