# Generated by Django 4.2.10 on 2025-05-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        # A tabela books_book já existe, então não precisamos criá-la novamente
    ]
