# Generated by Django 4.2.10 on 2025-05-12 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20250512_1143'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS books_book;",
            "SELECT 1;"
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(verbose_name='Descrição')),
                ('cover_image', models.ImageField(upload_to='covers/', verbose_name='Capa')),
                ('pdf_file', models.FileField(upload_to='books/', verbose_name='Arquivo PDF')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audiobooks/', verbose_name='Arquivo de Áudio')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['-created_at'],
            },
        ),
    ]
