# Generated by Django 4.2.10 on 2025-05-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20250512_1145'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS "books_book" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "title" varchar(255) NOT NULL,
                "slug" varchar(255) NOT NULL UNIQUE,
                "description" text NOT NULL,
                "cover_image" varchar(100) NOT NULL,
                "pdf_file" varchar(100) NOT NULL,
                "audio_file" varchar(100) NULL,
                "created_at" datetime NOT NULL,
                "updated_at" datetime NOT NULL
            );
            """,
            "DROP TABLE IF EXISTS books_book;"
        ),
    ]
