# Generated by Django 4.2.10 on 2025-05-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_create_books_table_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.FileField(upload_to='covers/', verbose_name='Capa'),
        ),
    ]
