# Generated by Django 4.2.10 on 2025-05-12 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_add_default_categories'),
        ('books', '0006_alter_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='categories.category', verbose_name='Categoria'),
        ),
    ]
