# Generated by Django 4.2.10 on 2025-05-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookcomment'),
        ('books', '0007_book_category'),
    ]

    operations = [
    ]
